#!/usr/bin/env node
// Generate low-quality thumbnails from the R2 image URLs referenced in lib/projects.js.
// Writes JPGs to public/thumbs/<hash>.jpg and emits a map at lib/thumbs.js.

import { createHash } from 'node:crypto';
import { mkdir, writeFile, access } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import sharp from 'sharp';
import { PROJECTS } from '../lib/projects.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUT_DIR = join(ROOT, 'public', 'thumbs');
const MAP_FILE = join(ROOT, 'lib', 'thumbs.js');

const THUMB_SIZE = 256;
const QUALITY = 45;
const CONCURRENCY = 8;

function hashUrl(url) {
    return createHash('sha1').update(url).digest('hex').slice(0, 16);
}

async function exists(path) {
    try {
        await access(path);
        return true;
    } catch {
        return false;
    }
}

async function processOne(url) {
    const hash = hashUrl(url);
    const outPath = join(OUT_DIR, `${hash}.jpg`);
    const publicPath = `/thumbs/${hash}.jpg`;
    if (await exists(outPath)) {
        return { url, publicPath, skipped: true };
    }
    try {
        const res = await fetch(url);
        if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
        const buf = Buffer.from(await res.arrayBuffer());
        await sharp(buf)
            .resize(THUMB_SIZE, THUMB_SIZE, { fit: 'cover', position: 'attention' })
            .jpeg({ quality: QUALITY, mozjpeg: true })
            .toFile(outPath);
        return { url, publicPath, skipped: false };
    } catch (err) {
        return { url, publicPath: null, error: err.message };
    }
}

async function runPool(items, worker, concurrency) {
    const results = new Array(items.length);
    let next = 0;
    async function pull() {
        while (true) {
            const idx = next++;
            if (idx >= items.length) return;
            results[idx] = await worker(items[idx]);
        }
    }
    await Promise.all(Array.from({ length: concurrency }, pull));
    return results;
}

function collectUrls(projects) {
    const seen = new Set();
    const urls = [];
    for (const p of projects) {
        const cover = p?.content?.CoverImage?.filename;
        if (cover && !seen.has(cover)) {
            seen.add(cover);
            urls.push(cover);
        }
        const extras = p?.content?.Images || [];
        for (const img of extras) {
            const f = img?.filename;
            if (f && !seen.has(f)) {
                seen.add(f);
                urls.push(f);
            }
        }
    }
    return urls;
}

async function main() {
    await mkdir(OUT_DIR, { recursive: true });
    const urls = collectUrls(PROJECTS);
    console.log(`Found ${urls.length} unique image URLs`);

    const t0 = Date.now();
    let done = 0;
    const results = await runPool(
        urls,
        async (url) => {
            const r = await processOne(url);
            done += 1;
            if (done % 25 === 0 || done === urls.length) {
                console.log(`  [${done}/${urls.length}] processed`);
            }
            return r;
        },
        CONCURRENCY,
    );
    const dt = ((Date.now() - t0) / 1000).toFixed(1);

    const ok = results.filter((r) => r.publicPath);
    const failed = results.filter((r) => !r.publicPath);
    const skipped = ok.filter((r) => r.skipped).length;
    console.log(`Done in ${dt}s — ${ok.length} ok (${skipped} already cached), ${failed.length} failed`);
    if (failed.length) {
        for (const f of failed.slice(0, 10)) console.log(`  FAIL ${f.url} :: ${f.error}`);
    }

    const map = Object.fromEntries(ok.map((r) => [r.url, r.publicPath]));
    const out =
        '// Auto-generated by scripts/generate-thumbs.mjs. Do not edit by hand.\n' +
        '// Maps full-res R2 URLs to local low-quality thumbnail paths under /public/thumbs/.\n\n' +
        `export const THUMBS = ${JSON.stringify(map, null, 2)};\n\n` +
        'export function thumb(url) {\n' +
        '    return (url && THUMBS[url]) || url;\n' +
        '}\n';
    await writeFile(MAP_FILE, out, 'utf8');
    console.log(`Wrote map: ${MAP_FILE} (${Object.keys(map).length} entries)`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
